"""add person links tables for software and hardware

Revision ID: a2b3c4d5e6f7
Revises: dde6be40f54f
Create Date: 2026-01-29 14:45:00.000000

"""

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import uuid

# revision identifiers, used by Alembic.
revision = "a2b3c4d5e6f7"
down_revision = "dde6be40f54f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "software_person_link",
        sa.Column(
            "person_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column(
            "software_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["software_id"],
            ["software.id"],
        ),
        sa.PrimaryKeyConstraint("person_id", "software_id", "id"),
        sa.UniqueConstraint(
            "person_id",
            "software_id",
            name="software_person_link_uc",
        ),
    )
    with op.batch_alter_table("software_person_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_software_person_link_person_id"),
            ["person_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_software_person_link_software_id"),
            ["software_id"],
            unique=False,
        )

    op.create_table(
        "hardware_item_person_link",
        sa.Column(
            "person_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column(
            "hardware_item_id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column(
            "id",
            sqlalchemy_utils.types.uuid.UUIDType(binary=False),
            default=uuid.uuid4,
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["person_id"],
            ["person.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hardware_item_id"],
            ["hardware_item.id"],
        ),
        sa.PrimaryKeyConstraint("person_id", "hardware_item_id", "id"),
        sa.UniqueConstraint(
            "person_id",
            "hardware_item_id",
            name="hardware_item_person_link_uc",
        ),
    )
    with op.batch_alter_table(
        "hardware_item_person_link", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_hardware_item_person_link_person_id"),
            ["person_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_hardware_item_person_link_hardware_item_id"),
            ["hardware_item_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "hardware_item_person_link", schema=None
    ) as batch_op:
        batch_op.drop_index(
            batch_op.f("ix_hardware_item_person_link_hardware_item_id")
        )
        batch_op.drop_index(batch_op.f("ix_hardware_item_person_link_person_id"))

    op.drop_table("hardware_item_person_link")

    with op.batch_alter_table("software_person_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_software_person_link_software_id"))
        batch_op.drop_index(batch_op.f("ix_software_person_link_person_id"))

    op.drop_table("software_person_link")
    # ### end Alembic commands ###
