"""add theme columns to person and organisation

Revision ID: b3c4d5e6f7g8
Revises: a2b3c4d5e6f7
Create Date: 2026-02-20 12:00:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b3c4d5e6f7g8"
down_revision = "a2b3c4d5e6f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("theme", sa.String(40), nullable=True, server_default="light")
        )

    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "default_theme", sa.String(40), nullable=True, server_default="light"
            )
        )

    # Migrate existing dark_theme_by_default to default_theme
    op.execute(
        "UPDATE organisation SET default_theme = 'dark' WHERE dark_theme_by_default = true"
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("organisation", schema=None) as batch_op:
        batch_op.drop_column("default_theme")

    with op.batch_alter_table("person", schema=None) as batch_op:
        batch_op.drop_column("theme")
    # ### end Alembic commands ###
